#!/bin/sh
echo '[git hook] executing spotlessApply to format code before commit'

# Run spotlessApply
if command -v gradle > /dev/null 2>&1
then
    gradle spotlessApply
else
  ./gradlew spotlessApply
fi

# Store the last exit code in a variable
RESULT=$?

# Stage formatting changes
git add -u

# Return the 'spotlessApply' exit code
exit $RESULT