#!/bin/sh
echo '[git hook] executing spotless:apply to format code before commit'

# Stash any unstaged changes
git stash -q --keep-index

# Run spotlessApply
# We pass in ratchetFrom here to ensure that we only format the files that have changed since the last commit
if command -v gradle > /dev/null 2>&1
then
  echo "Calling Gradle"
  gradle spotlessApply -PratchetFrom=HEAD
else
  echo "Calling Gradle Wrapper"
  ./gradlew spotlessApply -PratchetFrom=HEAD
fi

# Store the last exit code in a variable
RESULT=$?

# Stage formatting changes
git add -u

# Un-stash the stashed changes
git stash pop -q

# Return the 'spotlessApply' exit code
exit $RESULT
